"""add config_json to orderbook_runs

Revision ID: 3be05d81dae8
Revises: 5ae1f01805cc
Create Date: 2026-06-06 10:48:32.235250
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be05d81dae8'
down_revision: Union[str, None] = '5ae1f01805cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderbook_runs', sa.Column('config_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderbook_runs', 'config_json')
    # ### end Alembic commands ###
