"""add expires_at to exchange_keys

Revision ID: 53e3cdc26069
Revises: 76c28d7283e9
Create Date: 2026-06-17 01:58:11.056837
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e3cdc26069'
down_revision: Union[str, None] = '76c28d7283e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_keys', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_keys', 'expires_at')
    # ### end Alembic commands ###
