"""add_last_heartbeat_at_to_orderbook_runs

Revision ID: 6540cfcbd5e0
Revises: 8425e4763976
Create Date: 2026-06-07 21:11:50.852323
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6540cfcbd5e0'
down_revision: Union[str, None] = '8425e4763976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderbook_runs', sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderbook_runs', 'last_heartbeat_at')
    # ### end Alembic commands ###
