"""add mapped_confidence and mapped_reasoning to trading_signals

Revision ID: 76c28d7283e9
Revises: 78ffcbc6921e
Create Date: 2026-06-14 23:55:59.546494
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c28d7283e9'
down_revision: Union[str, None] = '78ffcbc6921e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_signals', sa.Column('mapped_confidence', sa.Float(), nullable=True))
    op.add_column('trading_signals', sa.Column('mapped_reasoning', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trading_signals', 'mapped_reasoning')
    op.drop_column('trading_signals', 'mapped_confidence')
    # ### end Alembic commands ###
