"""add_available_exchanges_to_trading_signals

Revision ID: 78ffcbc6921e
Revises: 005_create_exchange_keys
Create Date: 2026-06-12 20:02:50.889119
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78ffcbc6921e'
down_revision: Union[str, None] = '005_create_exchange_keys'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_keys_user_exchange'), table_name='exchange_keys', postgresql_where='(is_active = true)')
    op.add_column('trading_signals', sa.Column('mapped_available_exchanges', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trading_signals', 'mapped_available_exchanges')
    op.create_index(op.f('ix_exchange_keys_user_exchange'), 'exchange_keys', ['user_id', 'exchange'], unique=True, postgresql_where='(is_active = true)')
    # ### end Alembic commands ###
