"""add signal metrics to ob runs

Revision ID: 8425e4763976
Revises: 3be05d81dae8
Create Date: 2026-06-06 14:06:12.340548
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8425e4763976'
down_revision: Union[str, None] = '3be05d81dae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderbook_runs', sa.Column('signals_total', sa.Integer(), nullable=True))
    op.add_column('orderbook_runs', sa.Column('signals_rejected', sa.Integer(), nullable=True))
    op.add_column('orderbook_runs', sa.Column('signals_per_minute', sa.Float(), nullable=True))
    op.add_column('orderbook_runs', sa.Column('last_signal_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orderbook_runs', sa.Column('last_signal_type', sa.String(length=50), nullable=True))
    op.add_column('orderbook_runs', sa.Column('last_rejection_reason', sa.String(length=200), nullable=True))
    op.add_column('orderbook_runs', sa.Column('signal_summary_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderbook_runs', 'signal_summary_json')
    op.drop_column('orderbook_runs', 'last_rejection_reason')
    op.drop_column('orderbook_runs', 'last_signal_type')
    op.drop_column('orderbook_runs', 'last_signal_at')
    op.drop_column('orderbook_runs', 'signals_per_minute')
    op.drop_column('orderbook_runs', 'signals_rejected')
    op.drop_column('orderbook_runs', 'signals_total')
    # ### end Alembic commands ###
