"""add_orderbook_runs

Revision ID: 8f067507c522
Revises: 062072ea98e7
Create Date: 2026-06-05 16:08:00.034482
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f067507c522'
down_revision: Union[str, None] = '062072ea98e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderbook_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pair', sa.String(length=20), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('max_open_trades', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ob_runs_started_at', 'orderbook_runs', ['started_at'], unique=False)
    op.create_index('ix_ob_runs_user_status', 'orderbook_runs', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_orderbook_runs_status'), 'orderbook_runs', ['status'], unique=False)
    op.create_index(op.f('ix_orderbook_runs_user_id'), 'orderbook_runs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orderbook_runs_user_id'), table_name='orderbook_runs')
    op.drop_index(op.f('ix_orderbook_runs_status'), table_name='orderbook_runs')
    op.drop_index('ix_ob_runs_user_status', table_name='orderbook_runs')
    op.drop_index('ix_ob_runs_started_at', table_name='orderbook_runs')
    op.drop_table('orderbook_runs')
    # ### end Alembic commands ###
