"""add trading_signals table

Revision ID: c249fa55656c
Revises: 344f3bf7b637
Create Date: 2026-06-11 23:46:31.295811
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c249fa55656c'
down_revision: Union[str, None] = '344f3bf7b637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('pair', sa.String(length=30), nullable=False),
    sa.Column('price_range', sa.Float(), nullable=True),
    sa.Column('vol_60m', sa.Float(), nullable=True),
    sa.Column('vol_10m', sa.Float(), nullable=True),
    sa.Column('slope', sa.Float(), nullable=True),
    sa.Column('top_ratio', sa.Float(), nullable=True),
    sa.Column('bot_ratio', sa.Float(), nullable=True),
    sa.Column('mapped_strategy', sa.String(length=50), nullable=True),
    sa.Column('mapped_engine', sa.String(length=20), nullable=True),
    sa.Column('mapped_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mapped_exchange_fallback', sa.String(length=50), nullable=True),
    sa.Column('is_processed', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_signals_channel'), 'trading_signals', ['channel'], unique=False)
    op.create_index(op.f('ix_trading_signals_created_at'), 'trading_signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_trading_signals_pair'), 'trading_signals', ['pair'], unique=False)
    op.create_index(op.f('ix_trading_signals_user_id'), 'trading_signals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_signals_user_id'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_pair'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_created_at'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_channel'), table_name='trading_signals')
    op.drop_table('trading_signals')
    # ### end Alembic commands ###
