"""Pydantic dataclasses and domain models for the trading module."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class TradingRunMode(str, Enum):
    """Run mode for a trading strategy execution."""

    history = "history"
    virtual = "virtual"
    real = "real"


class TradingRunStatus(str, Enum):
    """Status of a trading run."""

    running = "running"
    done = "done"
    stopped = "stopped"
    error = "error"


@dataclass
class Candle:
    """OHLCV candle."""

    open: float
    high: float
    low: float
    close: float
    volume: float
    timestamp: datetime


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    side: str  # BUY / SELL
    price: float
    time: datetime
    type: str  # entry / exit
    confidence: float  # 0.0 – 1.0
    exit_target: Optional[float] = None  # Dynamic TP price (overrides config TP if set)


@dataclass
class Trade:
    """Represents a single completed or open trade."""

    side: str
    entry_price: float
    exit_price: Optional[float] = None
    entry_time: Optional[datetime] = None
    exit_time: Optional[datetime] = None
    quantity: float = 0.0
    pnl: float = 0.0
    exit_reason: Optional[str] = None
    pair: Optional[str] = None  # Which pair this trade belongs to
    exit_target: Optional[float] = None  # Dynamic TP price from strategy


@dataclass
class Metrics:
    """Aggregated performance metrics for a run."""

    total_trades: int = 0
    win_trades: int = 0
    loss_trades: int = 0
    win_rate: float = 0.0
    profit_loss: float = 0.0
    final_balance: float = 0.0
    max_drawdown: float = 0.0
    sharpe: float = 0.0
    progress: float = 0.0  # 0-100% for live runs


@dataclass
class TradingConfig:
    """Full configuration for a trading run."""

    mode: TradingRunMode = TradingRunMode.history
    pair: str = "BTCUSDT"
    strategy: str = "hammer"
    leverage: int = 1
    virtual_balance: float = 10000.0
    max_trade_amount: float = 1000.0
    timeframe: str = "1h"
    period_start: Optional[datetime] = None
    period_end: Optional[datetime] = None
    duration_days: Optional[int] = None
    exchange: Optional[str] = None
    stop_loss_percent: float = 1.0
    take_profit_percent: float = 5.0
    notification_bot_id: Optional[str] = None
    notification_bot_token: Optional[str] = None
    notification_chat_id: Optional[str] = None
    trend_filter_enabled: bool = True
    trend_filter_period: int = 200
    min_confidence: float = 0.3  # override default 0.3 threshold (used by micro-preset)


@dataclass
class TradingRun:
    """Aggregate representing a single trading run session."""

    id: int = 0
    user_id: int = 0
    status: TradingRunStatus = TradingRunStatus.running
    mode: TradingRunMode = TradingRunMode.history
    config: TradingConfig = field(default_factory=TradingConfig)
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None
    error: Optional[str] = None
